<?php
/**
 * Writes config/.db-runtime.php from the process environment (PHP CLI sees Docker env;
 * Apache mod_php often does not). Invoked from docker-entrypoint.sh.
 */
declare(strict_types=1);

$configDir = dirname(__DIR__) . '/config';
$target = $configDir . '/.db-runtime.php';
$host = getenv('DATADOCK_DB_HOST');
if ($host === false || $host === '') {
    if (is_file($target)) {
        unlink($target);
    }
    exit(0);
}

$dbname = getenv('DATADOCK_DB_NAME') ?: 'datadock';
$user = getenv('DATADOCK_DB_USER') ?: 'datadock';
$pass = getenv('DATADOCK_DB_PASSWORD');
if ($pass === false) {
    $pass = '';
}

$php = "<?php\n"
    . "// Generated by scripts/generate-db-runtime.php — do not commit.\n"
    . '$host = ' . var_export($host, true) . ";\n"
    . '$dbname = ' . var_export($dbname, true) . ";\n"
    . '$user = ' . var_export($user, true) . ";\n"
    . '$pass = ' . var_export($pass, true) . ";\n";

if (file_put_contents($target, $php) === false) {
    fwrite(STDERR, "DataDock: could not write {$target}\n");
    exit(1);
}

exit(0);
